apiVersion: apps/v1
kind: Deployment
metadata:
  name: everwrite-backend
  namespace: everwrite
  labels:
    app: everwrite-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: everwrite-backend
  template:
    metadata:
      labels:
        app: everwrite-backend
      annotations:
        annotations:
        prometheus.io/scrape: "true"
        prometheus.io.scheme: "http"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "4567"
    spec:
      containers:
        - name: everwrite-backend
          image: eshwarhs99/everwrite:backend
          imagePullPolicy: Always
          ports:
            - containerPort: 4567
          env:
            - name: PORT
              value: "4567"
            - name: MONGO_URL
              value: mongodb://root:passwd@everwrite-mongodb-service.everwrite.svc.cluster.local:27017
---
apiVersion: v1
kind: Service
metadata:
  name: everwrite-backend-service
  namespace: everwrite
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4567
  selector:
    app: everwrite-backend
