global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "everwrite"
    static_configs:
      - targets: ["everwrite-backend:4567"]
