name: Build and Push Backend Docker Image

on:
  push:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t eshwarhs99/everwrite:backend backend/
          docker tag eshwarhs99/everwrite:backend eshwarhs99/everwrite:backend

      - name: Push Docker image to registry
        run: |
          docker push eshwarhs99/everwrite:backend
